services:
  site:
    network_mode: "host"
    container_name: docsy
    command: bash -c "npm i . && npm run start"
    image: docker.io/library/node:latest@sha256:f9a1756160a9e1c3dca456bc0b185bf8f2f112a6771c694df87288046f4306f1
    working_dir: /srv/docs
    volumes:
      - "./:/srv/docs:Z"
    ports:
      - "3000:3000"
