name: Generate Docs PDF
on:
  schedule:
    - cron: "50 5 * * 0" # 5:50 UTC Weekly on Sundays
  workflow_dispatch:

jobs:
  pdf:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Cache Prince XML
        id: cache-prince
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            /usr/local/lib/prince
            /usr/local/bin/prince
          key: prince-15.4.1-linux-x86_64

      - name: Install Prince
        if: steps.cache-prince.outputs.cache-hit != 'true'
        run: |
          curl https://www.princexml.com/download/prince-15.4.1-linux-generic-x86_64.tar.gz -O
          tar zxf prince-15.4.1-linux-generic-x86_64.tar.gz
          cd prince-15.4.1-linux-generic-x86_64
          yes "" | sudo ./install.sh

      - name: Build PDF
        run: npx docusaurus-prince-pdf --toc -u https://docs.projectbluefin.io -o pdf/bluefin.pdf

      - name: Upload results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: bluefin
          # The output filename can be specified with --output option
          path: pdf/bluefin.pdf
          if-no-files-found: error
          overwrite: true

      - name: Upload Release Artifact
        if: github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload --clobber 0.1 pdf/bluefin.pdf
