name: Validate Renovate

on:
  pull_request:
    paths:
      - "**/renovate.json"
      - "**/renovate.json5"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install -g renovate

      - name: Validate Renovate config
        run: renovate-config-validator --strict
