name: Validate Renovate

on:
  pull_request:
    paths:
      - "**/renovate.json"
      - "**/renovate.json5"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install -g renovate@43.150.0

      - name: Validate Renovate config
        run: renovate-config-validator
